/*
 * generated by Xtext
 */
package org.tud.inf.st.smags.dsl;

import org.tud.inf.st.smags.dsl.DSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DSLStandaloneSetup extends DSLStandaloneSetupGenerated{

	public static void doSetup() {
		new DSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

