/**
 * generated by Xtext 2.10.0
 */
package org.tud.inf.st.smags.dsl;

import org.tud.inf.st.smags.dsl.DSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {
  public static void doSetup() {
    DSLStandaloneSetup _dSLStandaloneSetup = new DSLStandaloneSetup();
    _dSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
