/*
 * generated by Xtext 2.10.0
 */
package org.tud.inf.st.smags.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.tud.inf.st.smags.dsl.parser.antlr.internal.InternalDSLParser;
import org.tud.inf.st.smags.dsl.services.DSLGrammarAccess;

public class DSLParser extends AbstractAntlrParser {

	@Inject
	private DSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDSLParser createParser(XtextTokenStream stream) {
		return new InternalDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SmagsModel";
	}

	public DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
