/**
 * generated by Xtext 2.10.0
 */
package org.tud.inf.st.smags.dsl.validation;

import org.tud.inf.st.smags.dsl.validation.AbstractDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DSLValidator extends AbstractDSLValidator {
}
